#server.context-path=/
#server.port=8080
#
#
#mysql.jdbcUrl=jdbc:mysql://127.0.0.1:3306/data?characterEncoding=utf-8
#mysql.driverClassName=com.mysql.jdbc.Driver
#mysql.username=root
#mysql.password=hzzjy
server:
  context-path: /
  port: 8080
 
spring:
  datasource:
    url: jdbc:mysql://39.104.65.152:3306/data?characterEncoding=utf-8
    username: root
    password: Abc123**..
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
app: 
  id: 3533777
  key: 467894e58bb60d52b7361b1621e7c64e

#http://Aauth.139jy.cn/educloud/   
#http://121.41.62.98:9200/educloud_new/
url: 
  prefix: http://Aauth.139jy.cn/educloud/
  oauth: ucenter/oauth
  user: api/openAPI/v3/get_user_info
  userclass: api/openAPI/v2/get_user_class_info
  usercard: api/openAPI/v3/get_user_card_info

    
    
    
    