#server.context-path=/
#server.port=8080
#
#
#mysql.jdbcUrl=jdbc:mysql://127.0.0.1:3306/data?characterEncoding=utf-8
#mysql.driverClassName=com.mysql.jdbc.Driver
#mysql.username=root
#mysql.password=hzzjy
server:
  context-path: /
  port: 80
 
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/data?characterEncoding=utf-8
    username: root
    password: hzzjy
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
app: 
  id: appid
  key: appkey

#http://Aauth.139jy.cn/educloud/
url: 
  prefix: http://121.41.62.98:9200/educloud_new/
  oauth: ucenter/oauth

    
    
    
    